### ISSUE TITLE
downloading zip

### ISSUE THREAD

**Issue by soichih** [juanprietob/xnat-rest#1]
Hello!

Does this API wrapper allow me to download zipped dicom images? The XNAT API doc says I can do following.

https://wiki.xnat.org/docs16/4-developer-documentation/using-the-xnat-rest-api/downloading-files-via-xnat-rest-api
```
Do I have to download the files one by one?
No. You can use the query string parameter format=zip to return the actual files in a compressed archive instead of returning the list of files.

/data/archive/projects/TEST/subjects/1/experiments/MR1/scans/1/resources/DICOM/files?format=zip
```

How can I accomplish this via xnat-rest?

**Comment by juanprietob** [comment]
This function https://github.com/juanprietob/xnat-rest/blob/master/index.js#L575 would need to be modified to add the "format=zip" parameter.
